version: '1'
services:
  bot:
    image: bot_telegram_image
    container_name: rpg_bot
    working_dir: /bot
    volumes:
      - .:/bot
    ports:
      - "8081:8081"
    command: python3 adventure_bot.py
    tty: true
